set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN V17 [get_ports reset]
set_property PACKAGE_PIN U16 [get_ports led]
set_property PACKAGE_PIN W5 [get_ports clk]
create_clock -name sys_clk -period 10.0 [get_ports clk]